apiVersion: v1
kind: Service
metadata:
  name: ecommerce-backend-svc
spec:
  selector:
    app: ecommerce-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080 # Must match the containerPort above
  type: ClusterIP
